services:
  tw1zt3ds_iptv:
    image: ghcr.io/tw1zt3d2four7/tw1zt3ds_iptv/tw1zt3ds_iptv:latest
    container_name: tw1zt3ds_iptv
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3037:3037"  # Expose port 5000 for accessing the Flask app
    #command: gunicorn Tw1zT3ds_IPTV:app --workers 3 --bind 0.0.0.0:3036 --log-level info --access-logfile - --error-logfile - 
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ./config.yml:/config/config.yml
    environment:
      - FLASK_APP=Tw1zT3ds_IPTV.py  # Flask app entry point
      - FLASK_RUN_HOST=0.0.0.0  # Make the app accessible on all interfaces
      - FLASK_ENV=production
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker

